### ISSUE TITLE
Create a contributing.md file

### ISSUE THREAD

**Issue by itisaby** [acm-iem/VirtualMouse#4]
The file must contain all the guidelines required for the contributors while contributing to the project.

**Comment by lonewolf235** [comment]
Can you assign me these two issues of updating the readme file and contributing. md

**Comment by itisaby** [comment]
Yeah sure Go ahead :) @lonewolf235 make sure to link the issue while making a PR

**Comment by itisaby** [comment]
> Can you assign me these two issues of updating the readme file and contributing. md

Alright

**Comment by lonewolf235** [comment]
Created a pull request for the same, kindly review it.
